version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  broker1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9091:9091
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9091,EXTERNAL://0.0.0.0:9092,LAN://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker1:9091,EXTERNAL://localhost:9092,LAN://${DEVICE_IP}:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,LAN:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  broker2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9094:9094
      - 9095:9095
      - 9096:9096
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9094,EXTERNAL://0.0.0.0:9095,LAN://0.0.0.0:9096
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker2:9094,EXTERNAL://localhost:9095,LAN://${DEVICE_IP}:9096
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,LAN:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  broker3:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
      - broker1
      - broker2
    ports:
      - 9097:9097
      - 9098:9098
      - 9099:9099
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9097,EXTERNAL://0.0.0.0:9098,LAN://0.0.0.0:9099
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker3:9097,EXTERNAL://localhost:9098,LAN://${DEVICE_IP}:9099
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,LAN:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "bash", "-c", "kafka-topics --bootstrap-server broker3:9097 --list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  opensearch:
    image: opensearchproject/opensearch:latest
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - compatibility.override_main_response_version=true

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"

  football-producer:
    restart: always
    depends_on:
      broker3:
        condition: service_healthy
    build:
      context: ./scripts/football/producer

  football-consumer:
    restart: always
    depends_on: 
      - football-producer
      - opensearch-dashboards
    build:
      context: ./scripts/football/consumer
      
  basketball-producer:
    restart: always
    depends_on:
      broker3:
        condition: service_healthy
    build:
      context: ./scripts/basketball/producer
  
  basketball-producer2:
    restart: always
    depends_on:
      broker3:
        condition: service_healthy
    build:
      context: ./scripts/basketball/producer

  basketball-consumer:
    restart: always
    depends_on: 
      - basketball-producer
      - opensearch-dashboards
    build:
      context: ./scripts/basketball/consumer